services:
  reisetool:
    build: .
    container_name: reisetool
    ports:
      - '3000:3000'
    volumes:
      - /mnt/user/appdata/reisetool:/data
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
